compilation:
  cloud_properties: {}
  network: tomcat_network
  reuse_compilation_vms: true
  workers: 4
director_uuid: <%= `bosh target > /dev/null 2>&1 && bosh status --uuid` %>
iaas_settings:
  compilation_cloud_properties: {}
  resource_pool_cloud_properties:
  - cloud_properties: {}
    name: tomcat_z1
  - cloud_properties: {}
    name: errands_z1
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  subnet_configs:
  - name: tomcat_z1
    subnets:
    - cloud_properties:
        name: random
      range: 10.244.15.0/24
      reserved:
      - 10.244.15.1
      static:
      - 10.244.15.2 - 10.244.15.20
  watch_time: 10000-120000
jobs:
- instances: 1
  name: tomcat
  networks:
  - name: tomcat_network
  resource_pool: tomcat-resource-pool
  templates:
  - name: tomcat
meta:
  director_uuid: <%= `bosh target > /dev/null 2>&1 && bosh status --uuid` %>
name: tomcat
networks:
- name: tomcat_network
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.15.0/24
    reserved:
    - 10.244.15.1
    static:
    - 10.244.15.2 - 10.244.15.20
  type: manual
properties:
  nats:
    machines:
    - 10.244.0.6
    port: 4222
    user: nats
    password: nats

  tomcat:
    address: tomcat
    listen_port: 8080
    username: admin
    password: admin
    memory:
      max_heap: 1024
      min_heap: 1024

releases:
- name: tomcat-release
  version: latest
resource_pools:
- cloud_properties: {}
  name: tomcat-resource-pool
  network: tomcat_network
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 10000-120000
  max_in_flight: 1
  serial: true
  update_watch_time: 10000-120000
